#Employee API url
emp:
  api:
     url: http://localhost:8080/employee
kafka:
  boot:
    server: localhost:9092
  topic:
    name: myTopic-kafkasender
  consumer:
    group:
      id: myTopic-group-id
server:
  port: 8082